name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - python~=3.10.13
  - jupyterlite-core==0.2.2
  - jupyterlab~=4.0.9
  - notebook~=7.0.6
  - atap_corpus~=0.1.10
  - odfpy~=1.4.1
  - pandas~=2.1
  - panel~=1.3
  - pyreadr~=0.5.0
